### ISSUE TITLE
Negative values for receive level will captured as positive values

### ISSUE THREAD

**Issue by bredmich** [philfry/check_tc4400#3]
Hi there,

i found a bug or mishandling of negative receive level values.
I´m not sure if this is a Nagios oder check_tc4400 problem.
Nagios shows the OFDM values like this:
`dn32_cwcorr=266038494c;;; dn32_cwfail=1890470150c;;; dn32_cwpass=2621806538c;;; dn32_rlvl=0.4;;; dn32_snr=32.0`
While the TC4400 website shows the values like this:

Channel Index | Channel ID | Lock Status | Channel Type | Bonding Status | Center Frequency | Width | SNR/MER Threshold Value | Receive Level | Modulation/Profile ID | Unerrored Codewords | Corrected Codewords | Uncorrectable Codewords
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
32 | 32 | Locked | OFDM Downstream | Bonded | 823000000 Hz | 86000 kHz | 32.0 dB | -0.4 dBmV | 0, 1, 2 | 2622038028 | 266069980 | 1890579029

Could you pleas check if this is an bug of the check_tc4400 plugin?

kind regards
Michael

**Comment by philfry** [comment]
fixed, thanks :+1:
